project creates
AnvarjonShavqiyev/Tasks pull request #1
Opened 2024-06-24 15:59 UTC by AnvarjonShavqiyev

React app is created

2024-06-25 10:29 UTC, EugeneSinitsa requested changes

2024-06-25 10:29 UTC, EugeneSinitsa commented on my-react-app/README.md
> +# Getting Started with Create React App
It is better to cleanup readme.md file. I prefer to remove default text

2024-06-25 10:29 UTC, EugeneSinitsa commented on my-react-app/package.json
> +    "@testing-library/jest-dom": "^5.17.0",
Why do we need version autoincrementing?

2024-06-25 10:29 UTC, EugeneSinitsa commented on my-react-app/package.json
> +  "dependencies": {
split your deps between `dependencies` and `devDependencies`

2024-06-25 10:29 UTC, EugeneSinitsa commented on my-react-app/public/index.html
> +<!DOCTYPE html>
remove boilerplate

2024-06-25 10:29 UTC, EugeneSinitsa commented on my-react-app/public/robots.txt
> +# https://www.robotstxt.org/robotstxt.html
why do we need this file?

2024-06-25 10:29 UTC, EugeneSinitsa commented on my-react-app/src/App.test.tsx
> +test('renders learn react link', () => {
boilerplate. create another test

2024-06-25 10:29 UTC, EugeneSinitsa commented on my-react-app/src/App.tsx
> +    <div className="App">
boilerplate

2024-06-26 10:31 UTC, EugeneSinitsa approved these changes

2024-06-27 11:43 UTC, VladKetris approved these changes

2024-06-30 19:12 UTC, esnts commented
You can merge this one

2024-07-04 11:16 UTC, merged