Advanced auth front
AnvarjonShavqiyev/Tasks pull request #10
Opened 2024-07-05 15:26 UTC by AnvarjonShavqiyev

Integrated JWT authentication in the React app.
Created login and registration forms.
Stored the JWT token securely in the browser with localstorage.
Used the token to access protected endpoints.
 
![photo_2024-07-05_17-48-00](https://github.com/AnvarjonShavqiyev/Tasks/assets/129954447/c1ae79c6-7d68-4960-838b-d059690d1761)
![photo_2024-07-05_17-48-27](https://github.com/AnvarjonShavqiyev/Tasks/assets/129954447/3c8f5fbc-9283-4633-b90b-d547ab1c26ce)
![photo_2024-07-05_17-48-36](https://github.com/AnvarjonShavqiyev/Tasks/assets/129954447/56525f83-8733-498f-8244-be21b6093e5b)
![photo_2024-07-05_17-48-47](https://github.com/AnvarjonShavqiyev/Tasks/assets/129954447/46351fc9-ee37-4531-89cf-0648ec9e0df2)
![photo_2024-07-05_17-59-17](https://github.com/AnvarjonShavqiyev/Tasks/assets/129954447/20c384de-967d-4ba1-8e58-989fc197a93b)
![photo_2024-07-05_17-59-29 (2)](https://github.com/AnvarjonShavqiyev/Tasks/assets/129954447/553e9978-e664-47f1-b655-0d383732a25b)
![photo_2024-07-05_17-59-29](https://github.com/AnvarjonShavqiyev/Tasks/assets/129954447/f66fd7e1-fc05-4f9b-bfaa-dcc7bd7b5727)

2024-07-09 12:23 UTC, EugeneSinitsa requested changes

2024-07-09 12:41 UTC, AnvarjonShavqiyev commented on my-react-app/src/pages/Auth/signin/Signin.tsx
> +    console.log('Signin values:', values);
fixed

2024-07-09 12:41 UTC, AnvarjonShavqiyev commented on my-react-app/src/redux/features/AuthSlice.ts
>        console.log('Error creating user:', error);
fixed

2024-07-09 12:41 UTC, AnvarjonShavqiyev commented on my-react-app/src/redux/features/UsersSlice.ts
> +          Authorization: `Bearer ${token}`
Yeah, that is better way, i got it.

2024-07-11 19:39 UTC, esnts commented
merge it

2024-07-12 10:20 UTC, merged