Simple crud project
AnvarjonShavqiyev/Tasks pull request #6
Opened 2024-06-25 17:08 UTC by AnvarjonShavqiyev

2024-06-30 19:13 UTC, esnts commented on my-nest-project/package.json
> +    "@nestjs/cli": "^10.0.0",
We are not using version auto-incrementing `^`

2024-06-30 19:14 UTC, esnts commented on my-nest-project/src/app.module.ts
> +      url: "postgres://default:ZnU1ztG6ocdg@ep-white-snow-a47lu56s-pooler.us-east-1.aws.neon.tech:5432/verceldb?sslmode=require",
NEVER push credentionals.

2024-06-30 19:15 UTC, esnts commented on my-nest-project/src/controllers/user.controller.ts
> +            throw new BadRequestException('Failed to create user');
move all common errors/strings to file with constants

2024-07-01 09:44 UTC, AnvarjonShavqiyev commented on my-nest-project/package.json
> +    "@nestjs/cli": "^10.0.0",
i got it

2024-07-01 09:45 UTC, AnvarjonShavqiyev commented on my-nest-project/src/app.module.ts
> +      url: "postgres://default:ZnU1ztG6ocdg@ep-white-snow-a47lu56s-pooler.us-east-1.aws.neon.tech:5432/verceldb?sslmode=require",
I know about it, in these time i found vercel to free deployment, it was very interesting and i forget improve it.
I never push credentionls, i am sorry

2024-07-01 11:29 UTC, EugeneSinitsa requested changes

2024-07-01 11:29 UTC, EugeneSinitsa commented on my-nest-project/.env
> +DATABASE_URL="postgres://default:ZnU1ztG6ocdg@ep-white-snow-a47lu56s-pooler.us-east-1.aws.neon.tech:5432/verceldb?sslmode=require"
Create `.env.template` with  
```DATABASE_URL="..."```

2024-07-04 10:08 UTC, esnts commented
I still can find all credentials into your commits history 
<img width="1125" alt="Screenshot 2024-07-04 at 12 07 42" src="https://github.com/AnvarjonShavqiyev/Tasks/assets/44157749/de33aa3e-0065-4c79-ac1f-68c38d272252">


You can merge it after commits history clean up

2024-07-04 11:46 UTC, closed without merging